include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
    use_build_context_synchronously: ignore
    unused_element: ignore
    unused_import: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
